In [1]:
import numpy as np 

In [2]:
# Define matrices 
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[10, 11],
              [20, 21],
              [30, 31]])

In [3]:
A 
B  

array([[10, 11],
       [20, 21],
       [30, 31]])

In [4]:
# Simple Multiplication 
A @ B 

array([[140, 146],
       [320, 335]])

In [5]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Normal Multiplication (@):\n", A @ B)
print("\")
print("Hadamard Multiplication (*):\n", A * B)

Normal Multiplication (@):
 [[19 22]
 [43 50]]
Hadamard Multiplication (*):
 [[ 5 12]
 [21 32]]
