In [1]:
import numpy as np
import pandas as pd 

In [14]:
# Creating a Matrix
M1 = np.random.randint(10, 50, size=(3, 3))

In [15]:
M1

array([[21, 40, 23],
       [38, 27, 49],
       [36, 46, 26]], dtype=int32)

In [32]:
# Task A- Adding 50 to Matrix
M1+50   # this operation will not reflect to the original Matrix (M1)

array([[71, 90, 73],
       [88, 77, 99],
       [86, 96, 76]], dtype=int32)

In [23]:
# Task B- Subtracting 20 from Matrix
M1-20   # this operation will not reflect to the original Matrix (M1)

array([[ 1, 20,  3],
       [18,  7, 29],
       [16, 26,  6]], dtype=int32)

In [30]:
# Task C- Multiplying Matrix with 3 
M1*3   # this operation will not reflect to the original Matrix (M1)

array([[ 63, 120,  69],
       [114,  81, 147],
       [108, 138,  78]], dtype=int32)

In [31]:
# Task D- Deviding Matrix by 4 
M1/4   # this operation will not reflect to the original Matrix (M1)

array([[ 5.25, 10.  ,  5.75],
       [ 9.5 ,  6.75, 12.25],
       [ 9.  , 11.5 ,  6.5 ]])

### Task: Create two 3*3 matrices and then perform additon,subtraction,multiplication and division between these two metrices.

In [34]:
# Creating 2 more Matrix
M2 = np.random.randint(10, 50, size= (3, 3))
M3 = np.random.randint(10, 50, size= (3, 3))

In [36]:
M2

array([[35, 46, 21],
       [40, 38, 27],
       [42, 26, 16]], dtype=int32)

In [37]:
M3

array([[45, 47, 22],
       [42, 13, 26],
       [18, 46, 10]], dtype=int32)

In [39]:
# Task: Performing Addition between these Two Matrix
M2+M3

array([[80, 93, 43],
       [82, 51, 53],
       [60, 72, 26]], dtype=int32)

In [41]:
# Task: Performing Subtraction between these Two Matrix
M2-M3

array([[-10,  -1,  -1],
       [ -2,  25,   1],
       [ 24, -20,   6]], dtype=int32)

In [43]:
# Task: Performing Multiplication between these Two Matrix
M2*M3

array([[1575, 2162,  462],
       [1680,  494,  702],
       [ 756, 1196,  160]], dtype=int32)

In [44]:
# Task: Performing Division between these Two Matrix
M2/M3

array([[0.77777778, 0.9787234 , 0.95454545],
       [0.95238095, 2.92307692, 1.03846154],
       [2.33333333, 0.56521739, 1.6       ]])