In [1]:
import numpy as np
import pandas as pd 

In [14]:
# Creating a Matrix
M1 = np.random.randint(10, 50, size=(3, 3))

In [15]:
M1

array([[21, 40, 23],
       [38, 27, 49],
       [36, 46, 26]], dtype=int32)

In [32]:
# Task A- Adding 50 to Matrix
M1+50   # this operation will not reflect to the original Matrix (M1)

array([[71, 90, 73],
       [88, 77, 99],
       [86, 96, 76]], dtype=int32)

In [23]:
# Task B- Subtracting 20 from Matrix
M1-20   # this operation will not reflect to the original Matrix (M1)

array([[ 1, 20,  3],
       [18,  7, 29],
       [16, 26,  6]], dtype=int32)

In [30]:
# Task C- Multiplying Matrix with 3 
M1*3   # this operation will not reflect to the original Matrix (M1)

array([[ 63, 120,  69],
       [114,  81, 147],
       [108, 138,  78]], dtype=int32)

In [31]:
# Task D- Deviding Matrix by 4 
M1/4   # this operation will not reflect to the original Matrix (M1)

array([[ 5.25, 10.  ,  5.75],
       [ 9.5 ,  6.75, 12.25],
       [ 9.  , 11.5 ,  6.5 ]])

### Task: Create two 3*3 matrices and then perform additon,subtraction,multiplication and division between these two metrices.

In [34]:
# Creating 2 more Matrix
M2 = np.random.randint(10, 50, size= (3, 3))
M3 = np.random.randint(10, 50, size= (3, 3))

In [36]:
M2

array([[35, 46, 21],
       [40, 38, 27],
       [42, 26, 16]], dtype=int32)

In [37]:
M3

array([[45, 47, 22],
       [42, 13, 26],
       [18, 46, 10]], dtype=int32)

In [39]:
# Task: Performing Addition between these Two Matrix
M2+M3

array([[80, 93, 43],
       [82, 51, 53],
       [60, 72, 26]], dtype=int32)

In [41]:
# Task: Performing Subtraction between these Two Matrix
M2-M3

array([[-10,  -1,  -1],
       [ -2,  25,   1],
       [ 24, -20,   6]], dtype=int32)

In [43]:
# Task: Performing Multiplication between these Two Matrix
M2*M3

array([[1575, 2162,  462],
       [1680,  494,  702],
       [ 756, 1196,  160]], dtype=int32)

In [44]:
# Task: Performing Division between these Two Matrix
M2/M3

array([[0.77777778, 0.9787234 , 0.95454545],
       [0.95238095, 2.92307692, 1.03846154],
       [2.33333333, 0.56521739, 1.6       ]])

### Task: Perform dot product between two matrix of size(2*2).

In [47]:
# Creating 2x2 Matrix
M1=np.array([[12,14],[10,8]])
M2=np.array([[1,4],[20,16]])

print(M1)
print(M2)

[[12 14]
 [10  8]]
[[ 1  4]
 [20 16]]


In [49]:
# Performing Dot Product between created 2x2 Matrix
dot_prod = np.dot(M1,M2)
print(dot_prod)

[[292 272]
 [170 168]]


## **Note:** Columns of first matrix must be equal to rows of second matrix

# **Tanspose of the Metrix**
### Task: Create a 3*3 Matrix and perform its Tanspose.

In [54]:
# Creating a Matrix of 3*3
M1 = np.random.randint(10, 50, size= (3, 3))

In [55]:
M1

array([[17, 40, 41],
       [33, 32, 32],
       [28, 49, 21]], dtype=int32)

In [58]:
# Perform Task: Transpose 
trans_M1 = M1.T

In [59]:
trans_M1

array([[17, 33, 28],
       [40, 32, 49],
       [41, 32, 21]], dtype=int32)

## **Property 1: Tanspose of a Transposed matrix is the original Matrix**

In [64]:
# Transpose of a Transposed Matrix
trans_M1.T

array([[17, 40, 41],
       [33, 32, 32],
       [28, 49, 21]], dtype=int32)

## **Property 2: (Additive Property): (A+B).T = A.T + B.T**

In [65]:
A = np.array([[4,5],[3,8],[20,30]])
B = np.array([[12,14],[45,5],[9,8]])

x = (A+B).T
print(x)

y = A.T+B.T
print(y)

if np.array_equal(x,y):
  print("Additive property is True")

else:
  print("Additive Property id False")

[[16 48 29]
 [19 13 38]]
[[16 48 29]
 [19 13 38]]
Additive property is True


## **Property 3: Multiplication Property of the transpose: (AxB).T = B.T x A.T**

In [67]:
A = np.array([[4,3,1],[8,9,6],[7,5,7]])
B = np.array([[1,2,7],[3,4,5],[5,6,9]])

x = np.dot(A,B).T
print(x)
print()

y = B.T.dot(A.T)
print(y)

if np.array_equal(x,y):
  print("Multiplicative property is True")

else:
  print("Multiplicative Property id False")

[[ 18  65  57]
 [ 26  88  76]
 [ 52 155 137]]

[[ 18  65  57]
 [ 26  88  76]
 [ 52 155 137]]
Multiplicative property is True


# **Determinant**

In [68]:
M1 = np.random.randint(10, 50, size= (3, 3))
M1

array([[11, 22, 32],
       [15, 16, 13],
       [18, 41, 41]], dtype=int32)

In [69]:
# To find Detreminant
np.linalg.det(M1)

np.float64(3434.9999999999995)

# **Inverse**

In [70]:
# Tp find the inverse
M1_inv = np.linalg.inv(M1)

In [71]:
M1_inv

array([[ 0.03580786,  0.11935953, -0.0657933 ],
       [-0.11091703, -0.0363901 ,  0.09810771],
       [ 0.09519651, -0.01601164, -0.04483261]])

In [72]:
np.round(M1 @ M1_inv, decimals= 4)

array([[ 1.,  0., -0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

# **Rank**

The number of independent rows or colums in matrix.

In [73]:
A = np.array([[1,2],[2,4]])
np.linalg.matrix_rank(A)

np.int64(1)

In [74]:
A = np.array([[1,2],[5,6]])
np.linalg.matrix_rank(A)

np.int64(2)

# **Eigen Values and Eigen Vectors**

In [75]:
A = np.array([[1,5],[3,2]])
eigVal,eigVec = np.linalg.eig(A)

In [76]:
eigVal

array([-2.40512484,  5.40512484])

In [77]:
eigVec

array([[-0.82653237, -0.75033198],
       [ 0.56288918, -0.66106121]])