In [1]:
import numpy as np
import pandas as pd 

In [14]:
# Creating a Matrix
M1 = np.random.randint(10, 50, size=(3, 3))

In [15]:
M1

array([[21, 40, 23],
       [38, 27, 49],
       [36, 46, 26]], dtype=int32)

In [22]:
# Task A- Adding 50 to existing Matrix
M1+50   # this operation will not reflect to the original Matrix (M1)

array([[71, 90, 73],
       [88, 77, 99],
       [86, 96, 76]], dtype=int32)

In [23]:
# Task B- Subtracting 20 from Matrix
M1-20   # this operation will not reflect to the original Matrix (M1)

array([[ 1, 20,  3],
       [18,  7, 29],
       [16, 26,  6]], dtype=int32)