In [1]:
import numpy as np

In [2]:
np.arange(0,24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [4]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
arr3d.ndim

3

In [5]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
arr2 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2.shape

(3, 3)

In [8]:
arr2.size

9

In [9]:
arr2.ndim

2

In [10]:
arr2.dtype

dtype('int64')

In [11]:
array2 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]] ,dtype=float)

In [12]:
array2.dtype

dtype('float64')

In [13]:
farr = np.array([3,6,2,5])

In [14]:
farr.shape

(4,)

In [15]:
farr[1]=40
farr

array([ 3, 40,  2,  5])

In [16]:
np.arange(1,11)  # kind of (for loop with range)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(1,10,4)  # start end num : (from 1 - 10 distributes equely) num times = 4 times

array([ 1.,  4.,  7., 10.])

In [18]:
emp = np.empty(6)  
emp

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 2.44769668e-307,
       2.67020950e-306, 2.14321575e-312])

In [19]:
np.ones((6,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.full((5,2), 3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [22]:
np.array([3,5,7,2])

array([3, 5, 7, 2])

In [23]:
sanu = np.zeros((5,3))
sanu

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
sanu.ndim

2

In [25]:
a = np.zeros((2, 5, 3, 4))
a.ndim

4

In [26]:
np.random.rand(7)

array([0.09995838, 0.56101224, 0.12854142, 0.83515988, 0.36350806,
       0.92604347, 0.4275072 ])

In [27]:
j = np.arange(10)
j[9]

np.int64(9)

In [28]:
a = np.diag([1,2,3])
print(a)
print(f"Index of a 2x2 is : {a[2, 2]}")

[[1 0 0]
 [0 2 0]
 [0 0 3]]
Index of a 2x2 is : 3


In [29]:
a[2, 1] = 6   #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 6, 3]])

In [30]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a[1:8:2]  #start=1, end=8, step=2 

array([1, 3, 5, 7])

In [32]:
#combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [33]:
b = np.arange(5)
a[5:] = b[::-1] #assigning into a the reverse value of b 
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# Copies and Views
A slicing operation created a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use np.may_share_memory() to check if two arrays share the same memory block.

<b>When modigying the view, the original array is modified as well:<b>

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b = a[::2]  #storing indexes of 'a' along with there idx val in 'b'
b

array([0, 2, 4, 6, 8])

In [36]:
np.shares_memory(a,b) #as there indexes are same and stored 'a' val into 'b' , there memory location are same, output=True

True

In [37]:
b[0] = 10
print(b)
print(a)  #eventhough we modified 'b', it updated 'a' because both shares same memory

#the chanages in 'b' will be reflect in 'a' also because 'b' stores the values of 'a', which makes memory location same for both : a & b

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [38]:
a = np.arange(10)

#force a copy
c = a[::2].copy()  #here we are just forcefuly copying the value of 'a' into 'c'
c

array([0, 2, 4, 6, 8])

In [39]:
np.shares_memory(a,c)  #output:false, because we just copied the val, so that is why there memory location are not same

False

In [40]:
c[0] = 10  #assigning new val
a  #assigning val in 'c' will not reflect in 'a' because there memory location are not same

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Fancy Indexing
Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates couples not views.

<b>Using Boolean Mask<b>

In [41]:
a = np.random.randint(0, 20, 15)
a

array([15,  8,  9,  7,  0,  1, 15, 10,  3,  5, 14,  9, 18,  7, 12],
      dtype=int32)

In [42]:
mask = (a % 2 == 0)

In [43]:
#extracting mask variable operation
extract_from_a = a[mask]
extract_from_a

array([ 8,  0, 10, 14, 18, 12], dtype=int32)

<b> Indexing with a mask can be very useful to assign a new value to a sub-array: <b>

In [44]:
a[mask] = -1  #assigning 'mask' value with -1
a

array([15, -1,  9,  7, -1,  1, 15, -1,  3,  5, -1,  9, -1,  7, -1],
      dtype=int32)

<b>Indexing with an array of integers<b>

In [45]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [47]:
# New values can be assigned
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Practice Questions (Easy)

In [48]:
# Create a 1D NumPy array of numbers from 0 to 9.
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# Create a 3×3 NumPy array filled with all True values (Boolean type).
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
# Create a 2D NumPy array with shape (3, 3) containing random integers from 1 to 10 (inclusive).
np.random.randint(1, 11, size=(3, 3))

array([[ 8,  8,  1],
       [ 3,  7,  6],
       [ 7,  7, 10]], dtype=int32)

In [51]:
# Create a 1D NumPy array with 10 values evenly spaced between 0 and 1, inclusive.
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [52]:
# Create a 3×3 identity matrix using NumPy.
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# Given a NumPy array a = np.array([1, 2, 3, 4, 5]), how would you get a new array with the elements reversed?
a = np.arange(1,6)
a[::-1]

array([5, 4, 3, 2, 1])

In [54]:
# How would you reshape a 1D array of 9 elements into a 3×3 2D array using NumPy?
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
# How can you extract all even numbers from the NumPy array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])?

#Using Boolean Indexing
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = (a % 2 == 0)
print(a[b])

[2 4 6 8]


In [56]:
# How can you extract all even numbers from the NumPy array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])?

#Using Boolean Indexing
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
approach = a[a % 2 == 0]
print(approach)

[2 4 6 8]


In [57]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

# ChatGPT Basic Practice Questions

In [58]:
# Q: Create a 1D NumPy array of integers from 0 to 9 and print only the even numbers.
d = np.arange(9)
print(d[d % 2 == 0])

[0 2 4 6 8]


In [59]:
# Q: Create a 1D NumPy array of integers from 10 to 20 (inclusive) and print only the numbers that are divisible by 3.
d = np.arange(10, 21)
print(d[d % 3 == 0])

[12 15 18]


In [60]:
# Q: Create a 1D NumPy array of 5 random integers between 1 and 100 (inclusive), and print the maximum and minimum values from the array.
d = np.random.randint(1, 101, 5)
print(d)

[85 98 16 52 94]


In [61]:
# Q: Create a 1D NumPy array of 10 numbers linearly spaced between 0 and 1 (inclusive), and print the array.
d = np.linspace(0, 2, 10)
print(d)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [62]:
# Q: Create a 3x3 NumPy array with values from 1 to 9, and print the sum of each row.
d = np.arange(1, 10)       
d = d.reshape(3, 3)          
print("Array:\n", d)
print("Row-wise sum:", d.sum(axis=1))

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row-wise sum: [ 6 15 24]


In [63]:
# Q: Create a 4x4 NumPy array with values from 1 to 16, and print the elements on its main diagonal.
d = np.arange(1, 17)
d = d.reshape(4, 4)
print("Array:\n", d)
print("Main diagonal:", np.diag(d))

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Main diagonal: [ 1  6 11 16]


In [64]:
# Q: Create a 1D NumPy array with values [3, 7, 1, 9, 2], and sort the array in ascending order.
a = np.array([3, 7, 1, 9, 2])
sorted_a = np.sort(a)
print("Original array:", a)
print("Sorted array:  ", sorted_a)

Original array: [3 7 1 9 2]
Sorted array:   [1 2 3 7 9]


In [65]:
# Q1: Create a 1D NumPy array with values from 0 to 20 (inclusive), and print only the values that are divisible by 4.
arr1 = np.arange(0, 21)
print("Numbers divisible by 4:", arr1[arr1 % 4 == 0])

Numbers divisible by 4: [ 0  4  8 12 16 20]


In [66]:
# Q2: Create a 3x3 NumPy array with values from 1 to 9, and print the sum of all elements.
arr2 = np.arange(1, 10).reshape(3, 3)
print("3x3 Array:\n", arr2)
print("Sum of all elements:", arr2.sum())

3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45


In [67]:
# Q3: Create a NumPy array of 6 random floating-point numbers between 0 and 1, and print the maximum value.
arr3 = np.random.rand(6)
print("Random values:", arr3)
print("Maximum value:", arr3.max())

Random values: [0.97403093 0.47167316 0.1359415  0.76476423 0.36234951 0.07534088]
Maximum value: 0.9740309343176176


In [68]:
# Q1: Create a NumPy array of 5 zeros
# Create a NumPy array with 5 zeros
zeros_array = np.zeros(5)
# Output the array
print("Question 1 Answer:", zeros_array)

Question 1 Answer: [0. 0. 0. 0. 0.]


In [69]:
# Q3: Find the mean of a NumPy array
# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Calculate the mean of the array
mean_value = np.mean(arr)

# Output the mean
print("Question 3 Answer:", mean_value)

Question 3 Answer: 30.0


In [70]:
# Q4: Create a NumPy array of even numbers from 2 to 20
# Create an array of even numbers from 2 to 20
even_array = np.arange(2, 21, 2)

# Output the array
print("Question 4 Answer:", even_array)

Question 4 Answer: [ 2  4  6  8 10 12 14 16 18 20]


In [71]:
# Q5: Create a 3×3 identity matrix
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

# Output the matrix
print("Question 5 Answer:\n", identity_matrix)

Question 5 Answer:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
# Q6: Find the maximum value in a NumPy array
# Create a NumPy array
arr = np.array([15, 42, 7, 89, 23])

# Find the maximum value
max_value = np.max(arr)

# Output the maximum value
print("Question 6 Answer:", max_value)

Question 6 Answer: 89


In [73]:
# Q7: Reshape a 1D array into a 3×3 matrix
# Create a 1D array from 1 to 9
arr = np.arange(1, 10)

# Reshape it into a 3x3 matrix
reshaped_arr = arr.reshape(3, 3)

# Output the reshaped array
print("Question 7 Answer:\n", reshaped_arr)

Question 7 Answer:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
# Q8: Element-wise addition of two NumPy arrays
# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Add them element-wise
sum_array = arr1 + arr2

# Output the sum
print("Question 8 Answer:", sum_array)

Question 8 Answer: [5 7 9]


In [75]:
# Q9: Create an array of 5 random integers between 10 and 50
# Create an array of random integers between 10 and 50
random_array = np.random.randint(10, 51, 5)

# Output the array
print("Question 9 Answer:", random_array)

Question 9 Answer: [33 25 49 27 50]


In [76]:
# Q10: Get the square of each element in a NumPy array
# Create a NumPy array
arr = np.array([2, 4, 6])

# Get the square of each element
squared_arr = arr ** 2

# Output the squared array
print("Question 10 Answer:", squared_arr)

Question 10 Answer: [ 4 16 36]


In [77]:
# Q11: Check which elements are greater than 10 in an array
# Create a NumPy array
arr = np.array([5, 12, 7, 15, 3])

# Check condition
greater_than_10 = arr > 10

# Output the boolean result
print("Question 11 Answer:", greater_than_10)

Question 11 Answer: [False  True False  True False]


In [78]:
# Create a NumPy array of odd numbers from 1 to 15
import numpy as np
odd_array = np.arange(1, 16, 2)
print(odd_array)

[ 1  3  5  7  9 11 13 15]


In [79]:
# Find the sum of all elements in a NumPy array
arr = np.array([4, 8, 15, 16, 23, 42])
total_sum = np.sum(arr)
print(total_sum)

108


In [80]:
# Create a 4x4 matrix with values from 1 to 16
import numpy as np
matrix = np.arange(1, 17).reshape(4, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [81]:
# Generate a NumPy array of 6 random floating-point numbers between 0 and 1
random_floats = np.random.rand(6)
print(random_floats)

[0.49055066 0.5923117  0.4446606  0.2256391  0.86313241 0.80062351]


In [82]:
# Replace all elements greater than 5 in an array with 0
arr = np.array([2, 6, 3, 9, 4, 7])
arr[arr > 5] = 0
print(arr)

[2 0 3 0 4 0]


In [83]:
# Multiply two NumPy arrays element-wise
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(result)

[ 4 10 18]


In [84]:
# Create a NumPy array of 10 ones
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [86]:
k = np.zeros((3, 4))
k

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
k = np.ones((3, 4), dtype='int')
print(k)
print('k Data Type is:', k.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
k Data Type is: int64


In [98]:
k = np.full((2, 3), 5)   # first brackets are shape like 2 rows and 3 columns and after that the value which we want only to fill with
k

array([[5, 5, 5],
       [5, 5, 5]])

In [101]:
k = np.arange(2, 8, 2)   # start stop step
k

array([2, 4, 6])

In [103]:
k = np.linspace(2, 8, 1)
k

array([2.])