In [1]:
import numpy as np 

# <b>1. Array Creation

# <b>np.array

In [2]:
"""
np.array()
----------
Kya karta hai?
Python list ya kisi bhi sequence ko NumPy array mein convert karta hai.

Syntax:
-------
np.array(object, dtype=None)

Must Parameters:
-----------------
object - Ye zaruri hai!
         List, tuple, ya koi sequence jo aap array banana chahte ho

Important Optional Parameters:
-------------------------------
dtype - Data type specify karne ke liye
        int, float, str, etc.
        Agar nahi dete toh NumPy khud detect kar leta hai
"""

# 1. Simple 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("Array1:", arr1, "\n")

# 2. 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array2:", arr2, "\n")

# 3. dtype specify karna
arr3 = np.array([1, 2, 3], dtype=float)
print("Array3:", arr3, "\n")

# 4. String se integer
arr4 = np.array(['1', '2', '3'], dtype=int)
print("Array4:", arr4, "\n")

Array1: [1 2 3 4 5] 

Array2: [[1 2 3]
 [4 5 6]] 

Array3: [1. 2. 3.] 

Array4: [1 2 3] 



# <b>np.zeros

In [3]:
"""
np.zeros()
----------
Kya karta hai?
Ek array banata hai jo puri tarah zeros (0) se bhara hota hai. ML mein initialization ke liye bahut use hota hai.

Syntax:
-------
np.zeros(shape, dtype=float)

Must Parameters:
-----------------
shape - Ye zaruri hai!
        Integer (1D array ke liye) ya Tuple (2D, 3D ke liye)
        Batata hai ki kitne rows aur columns chahiye

Important Optional Parameters:
-------------------------------
dtype - Data type (default: float)
        int, float, bool, etc.
"""

# 1. 1D array - 5 zeros
arr1 = np.zeros(5)
print("Array1:", arr1, "\n")

# 2. 2D array - 3 rows, 4 columns
arr2 = np.zeros((3, 4))
print("Array2:", arr2, "\n")

# 3. Integer type zeros
arr3 = np.zeros((2, 3), dtype=int)
print("Array3:", arr3, "\n")

# 4. 3D array - ML mein images ke liye
arr4 = np.zeros((2, 3, 3))
print("Array4 shape:", arr4.shape)
print("Array4:", arr4, "\n")

Array1: [0. 0. 0. 0. 0.] 

Array2: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Array3: [[0 0 0]
 [0 0 0]] 

Array4 shape: (2, 3, 3)
Array4: [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] 



# <b>np.ones

In [4]:
"""
np.ones()
----------
Kya karta hai?
Ek array banata hai jo puri tarah ones (1) se bhara hota hai. Weights initialization ya mask banane mein use hota hai.

Syntax:
-------
np.ones(shape, dtype=float) 

Must Parameters:
-----------------
shape - Ye zaruri hai!
       Integer (1D array ke liye) ya Tuple (2D, 3D ke liye)

Important Optional Parameters:
-------------------------------
dtype - Data type (default: float)
        int, float, bool, etc.
"""

# 1. 1D array - 5 ones
arr1 = np.ones(5)
print("Array1:", arr1, "\n")

# 2. 2D array - 3 rows, 4 columns
arr2 = np.ones((3, 4))
print("Array2:", arr2, "\n")

# 3. Integer type ones
arr3 = np.ones((2, 3), dtype=int)
print("Array3:", arr3, "\n")

# 4. 3D array
arr4 = np.ones((2, 2, 3))
print("Array4 shape:", arr4.shape)
print("Array4:", arr4, "\n")

Array1: [1. 1. 1. 1. 1.] 

Array2: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Array3: [[1 1 1]
 [1 1 1]] 

Array4 shape: (2, 2, 3)
Array4: [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]] 



# <b>np.full

In [5]:
"""
np.full()
----------
Kya karta hai?
Ek array banata hai jo kisi specific value se pura bhara hota hai. Jab aapko custom value se array initialize karna ho.

Syntax:
-------
np.full(shape, fill_value, dtype=None)

Must Parameters:
-----------------
shape - Ye zaruri hai!
        Integer (1D array ke liye) ya Tuple (2D, 3D ke liye)

fill_value - Ye bhi zaruri hai!
             Kon si value se array bharna hai

Important Optional Parameters:
-------------------------------
dtype - Data type (default: fill_value ka type)
        int, float, str, etc.
"""

# 1. 1D array - 5 elements with value 7
arr1 = np.full(5, 7)
print("Array1:", arr1, "\n")

# 2. 2D array - 3x4 matrix with value 3.14
arr2 = np.full((3, 4), 3.14)
print("Array2:", arr2, "\n")

# 3. Integer type with value 10
arr3 = np.full((2, 3), 10, dtype=int)
print("Array3:", arr3, "\n")

# 4. String value se bharna
arr4 = np.full((2, 2), 'Hi')
print("Array4:", arr4, "\n")

Array1: [7 7 7 7 7] 

Array2: [[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]] 

Array3: [[10 10 10]
 [10 10 10]] 

Array4: [['Hi' 'Hi']
 ['Hi' 'Hi']] 



# <b>np.arange

In [6]:
"""
np.arange()
-----------
Kya karta hai?
Python ke range() jaise kaam karta hai - ek sequence banata hai given range mein. Evenly spaced values generate karta hai.

Syntax:
-------
np.arange(start, stop, step, dtype=None)

Must Parameters:
-----------------
stop - Ye zaruri hai (agar sirf ek value dete ho)
       Yaha tak values generate hongi (stop inclusive nahi hota)

Important Optional Parameters:
-------------------------------
start - Starting value (default: 0)
        Kaha se start karna hai

step - Increment value (default: 1)
       Kitna gap rakhna hai values mein

dtype - Data type
        int, float, etc.
"""

# 1. Simple - 0 se 9 tak
arr1 = np.arange(10)
print("Array1:", arr1, "\n")

# 2. Start aur stop dono - 5 se 15 tak
arr2 = np.arange(5, 15)
print("Array2:", arr2, "\n")

# 3. Start, stop, step - 0 se 20 tak, 2-2 ka gap
arr3 = np.arange(0, 20, 2)
print("Array3:", arr3, "\n")

# 4. Float values - 0 se 1 tak, 0.1 ka gap
arr4 = np.arange(0, 1, 0.1)
print("Array4:", arr4, "\n")

# 5. Negative values
arr5 = np.arange(10, 0, -1)
print("Array5:", arr5, "\n")

Array1: [0 1 2 3 4 5 6 7 8 9] 

Array2: [ 5  6  7  8  9 10 11 12 13 14] 

Array3: [ 0  2  4  6  8 10 12 14 16 18] 

Array4: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9] 

Array5: [10  9  8  7  6  5  4  3  2  1] 



# <b>np.linspace

In [7]:
"""
np.linspace()
-------------
Kya karta hai?
Start aur stop ke beech mein equally spaced values generate karta hai. Aap kitni values chahiye wo specify karte ho.
arange() se fark: yaha step nahi, balki "kitni values chahiye" batate ho.

Syntax:
-------
np.linspace(start, stop, num=50, endpoint=True, dtype=None)

Must Parameters:
-----------------
start - Ye zaruri hai!
        Starting value

stop - Ye zaruri hai!
       Ending value

Important Optional Parameters:
-------------------------------
num - Kitni values generate karni hai (default: 50)
      Total number of values

endpoint - stop value include karna hai ya nahi (default: True)
           True = stop included, False = stop excluded

dtype - Data type
        int, float, etc.
"""

# 1. 0 se 10 tak, 5 equally spaced values
arr1 = np.linspace(0, 10, 5)
print("Array1:", arr1, "\n")

# 2. 0 se 1 tak, 11 values (0.1 ka gap)
arr2 = np.linspace(0, 1, 11)
print("Array2:", arr2, "\n")

# 3. endpoint=False - last value excluded
arr3 = np.linspace(0, 10, 5, endpoint=False)
print("Array3:", arr3, "\n")

# 4. Negative range
arr4 = np.linspace(-5, 5, 11)
print("Array4:", arr4, "\n")

# 5. Integer type
arr5 = np.linspace(0, 100, 6, dtype=int)
print("Array5:", arr5, "\n")

Array1: [ 0.   2.5  5.   7.5 10. ] 

Array2: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 

Array3: [0. 2. 4. 6. 8.] 

Array4: [-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.] 

Array5: [  0  20  40  60  80 100] 



# <b>np.eye 

In [9]:
"""
np.eye()
--------
Kya karta hai?
Identity matrix banata hai - diagonal par 1 aur baaki jagah 0. Linear algebra aur ML mein bahut use hota hai.

Syntax:
-------
np.eye(N, M=None, k=0, dtype=float)

Must Parameters:
-----------------
N - Ye zaruri hai!
    Number of rows

Important Optional Parameters:
-------------------------------
M - Number of columns (default: N)
    Agar nahi dete toh square matrix banta hai (N x N)

k - Diagonal index (default: 0)
    0 = main diagonal
    Positive = upper diagonal
    Negative = lower diagonal

dtype - Data type (default: float)
        int, float, etc.
"""

# 1. Simple 3x3 identity matrix
arr1 = np.eye(3)
print("Array1:", arr1, "\n")

# 2. 4x4 identity matrix
arr2 = np.eye(4)
print("Array2:", arr2, "\n")

# 3. Non-square matrix - 3 rows, 5 columns
arr3 = np.eye(3, 5)
print("Array3:", arr3, "\n")

# 4. Upper diagonal (k=1)
arr4 = np.eye(4, k=1)
print("Array4:", arr4, "\n")

# 5. Lower diagonal (k=-1)
arr5 = np.eye(4, k=-1)
print("Array5:", arr5, "\n")

# 6. Integer type
arr6 = np.eye(3, dtype=int)
print("Array6:", arr6, "\n")

Array1: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Array2: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

Array3: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]] 

Array4: [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]] 

Array5: [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] 

Array6: [[1 0 0]
 [0 1 0]
 [0 0 1]] 

